catalogMode: prefer
cleanupUnusedCatalogs: true

minimumReleaseAge: 10080

shellEmulator: true
trustPolicy: no-downgrade

packages:
  - packages/*
  - apps/*

catalog:
  jotai: ^2.19.1
  jotai-effect: ^2.2.3
  jotai-family: ^1.0.1
  react: ^19.2.5
