packages:
  - packages/*
  - apps/*

catalog:
  '@base-ui/react': ^1.4.1
  eslint-plugin-tailwindcss: 4.0.0-alpha.2
  jotai: ^2.19.1
  jotai-effect: ^2.2.3
  jotai-family: ^1.0.1
  react: ^19.2.5
catalogMode: prefer
cleanupUnusedCatalogs: true

minimumReleaseAge: 10080

shellEmulator: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - reselect
