export const IRREGULAR: Array<any> = [
  ["are", "aren't", "ain't", "were", "weren't"],
  ["awake", "awoke", "awoken"],
  ["be", "been"],
  ["beat", "beat", "beaten"],
  ["become", "became", "become"],
  ["begin", "began", "begun", "beginning"],
  ["bend", "bent"],
  ["bite", "bitten"],
  ["blow", "blew", "blown"],
  ["break", "broke", "broken"],
  ["bring", "brought"],
  ["build", "built"],
  ["burn", "burned", "burnt"],
  ["buy", "bought"],
  ["can", "can't"],
  ["catch", "caught"],
  ["choose", "chose", "chosen"],
  ["could", "couldn't"],
  ["come", "came",],
  ["dare", "daren't"],
  ["draw", "drew", "drawn"],
  ["dig", "dug"],
  ["do", "did", "done", "don't", "doesn't", "didn't"],
  ["dream", "dreamed", "dreamt"],
  ["drive", "drove", "driven"],
  ["drink", "drank", "drunk"],
  ["eat", "ate", "eaten"],
  ["fall", "fell", "fallen"],
  ["feel", "felt"],
  ["fight", "fought"],
  ["fly", "flew", "flown"],
  ["forget", "forgot", "forgotten"],
  ["forgive", "forgave", "forgiven"],
  ["freeze", "froze", "frozen"],
  ["get", "got", "gotten"],
  ["give", "gave", "given"],
  ["go", "went", "gone"],
  ["grow", "grew", "grown"],
  ["hang", "hung"],
  ["have", "has", "had", "haven't", "hasn't", "hadn't"],
  ["hear", "heard"],
  ["hide", "hid", "hidden"],
  ["hold", "held"],
  ["is", "was", "isn't", "wasn't",],
  ["I", "I'm",],
  ["keep", "kept"],
  ["know", "knew", "known"],
  ["lay", "laid", "laying"],
  ["lead", "led"],
  ["learn", "learned", "learnt"],
  ["lend", "lent"],
  ["lie", "lying"],
  ["make", "made"],
  ["mean", "meant"],
  ["meet", "met"],
  ["might", "mightn't"],
  ["must", "mustn't"],
  ["need", "needn't"],
  ["ought", "oughtn't"],
  ["pay", "paid"],
  ["put", "putting"],
  ["ride", "rode", "ridden"],
  ["ring", "rang", "rung"],
  ["rise", "rose", "risen"],
  ["run", "ran"],
  ["say", "said"],
  ["see", "seen"],
  ["sell", "sold"],
  ["send", "sent"],
  ["shall", "shan't"],
  ["should", "shouldn't"],
  ["show", "showed", "shown"],
  ["sing", "sang", "sung"],
  ["sink", "sank", "sunk"],
  ["sit", "sat"],
  ["sleep", "slept"],
  ["speak", "spoke", "spoken"],
  ["spend", "spent"],
  ["stand", "stood"],
  ["steal", "stole", "stolen"],
  ["stink", "stank", "stunk"],
  // ["swim", "swam", "swum"],
  ["take", "took", "taken"],
  ["teach", "taught"],
  ["tear", "tore", "torn"],
  ["tell", "told"],
  ["think", "thought"],
  ["throw", "threw", "thrown"],
  ["understand", "understood"],
  ["wake", "woke", "woken"],
  ["we", "we'll", "we've",],
  ["wear", "wore", "worn"],
  ["will", "won't",],
  ["win", "won"],
  ["would", "wouldn't"],
  ["write", "wrote", "written"],
]
