export const IRREGULAR: Array<any> = [
  ["are", "aren't", "ain't", "were", "weren't"],
  ["be", "been"],
  ["begin", "began", "begun", "beginning"],
  ["can", "can't"],
  ["could", "couldn't"],
  ["come", "came",],
  ["dare", "daren't"],
  ["draw", "drawn"],
  ["do", "done", "don't", "doesn't", "didn't"],
  ["have", "has", "had", "haven't", "hasn't", "hadn't"],
  ["is", "was", "isn't", "wasn't",],
  ["I", "I'm",],
  ["might", "mightn't"],
  ["must", "mustn't"],
  ["need", "needn't"],
  ["ought", "oughtn't"],
  ["shall", "shan't"],
  ["should", "shouldn't"],
  ["we", "we'll", "we've",],
  ["wear", "worn"],
  ["will", "won't",],
  ["would", "wouldn't"],
]
